# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-29 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theapp', '0004_auto_20171129_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('SP', 'Sport'), ('BS', 'Business')], max_length=2),
        ),
    ]
